name: Generate prebuilt archives
on: [push, pull_request]
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out project
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      with:
        cache: false
    - name: Set up rust caching
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "download/nx-decomp-tools/viking"
        cache-directories: |
          download/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-16.04
          download/clang+llvm-4.0.1-x86_64-linux-gnu-Fedora-25
    - name: Generate prebuilt archives
      run: ./generate.sh
    - uses: actions/upload-artifact@v4
      with:
        name: OdysseyDecomp-binaries_Linux
        path: build/OdysseyDecomp-binaries_Linux.tar.xz
    - uses: actions/upload-artifact@v4
      with:
        name: OdysseyDecomp-libcxx-headers
        path: build/OdysseyDecomp-libcxx-headers.tar.xz
    - uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/master'
      with:
        tag_name: v${{ github.run_number }}
        files: |
          build/OdysseyDecomp-binaries_Linux.tar.xz
          build/OdysseyDecomp-libcxx-headers.tar.xz
        preserve_order: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        make_latest: true
