name: Generate prebuilt archives
on: [push, pull_request]
permissions:
  contents: write

jobs:
  # Seperate release creation workflow that runs first to avoid a race condition
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        if: startsWith(github.ref, 'refs/tags/')
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          make_latest: true

  generate_x86_linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
    - name: Check out project
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Build and upload tools tarball for x86_64 Linux
      uses: ./.github/actions/build-and-upload-tarball-for-platform
      with:
        platform: x86_64-Linux
        install_llvm_build_deps_hook: |
          sudo apt update && sudo apt install cmake ninja-build -y
          wget http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7_2.7.18-13ubuntu1.5_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-stdlib_2.7.18-13ubuntu1.5_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb http://security.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb && sudo apt install ./libpython2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb ./libpython2.7-stdlib_2.7.18-13ubuntu1.5_amd64.deb ./python2.7-minimal_2.7.18-13ubuntu1.5_amd64.deb ./python2.7_2.7.18-13ubuntu1.5_amd64.deb -y

  generate_arm64_linux:
    needs: create_release
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Check out project
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Build and upload tools tarball for arm64 Linux
      uses: ./.github/actions/build-and-upload-tarball-for-platform
      with:
        platform: aarch64-Linux
        # https://askubuntu.com/questions/1527867/python-2-7-12-install-on-ubuntu-22-04
        install_llvm_build_deps_hook: |
          sudo apt update && sudo apt install cmake ninja-build -y
          wget https://ports.ubuntu.com/ubuntu-ports/pool/universe/p/python2.7/python2.7_2.7.18-13ubuntu1.5_arm64.deb https://ports.ubuntu.com/ubuntu-ports/pool/universe/p/python2.7/libpython2.7-stdlib_2.7.18-13ubuntu1.5_arm64.deb https://ports.ubuntu.com/ubuntu-ports/pool/universe/p/python2.7/python2.7-minimal_2.7.18-13ubuntu1.5_arm64.deb https://ports.ubuntu.com/ubuntu-ports/pool/universe/p/python2.7/libpython2.7-minimal_2.7.18-13ubuntu1.5_arm64.deb && sudo apt install ./libpython2.7-minimal_2.7.18-13ubuntu1.5_arm64.deb ./libpython2.7-stdlib_2.7.18-13ubuntu1.5_arm64.deb ./python2.7-minimal_2.7.18-13ubuntu1.5_arm64.deb ./python2.7_2.7.18-13ubuntu1.5_arm64.deb -y

  generate_arm64_darwin:
    needs: create_release
    runs-on: macos-latest
    steps:
    - name: Check out project
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Build and upload tools tarball for arm64 Darwin
      uses: ./.github/actions/build-and-upload-tarball-for-platform
      with:
        platform: arm64-Darwin
        install_llvm_build_deps_hook: |
          # FIXME use `pyenv --head` to work around
          #  https://github.com/pyenv/pyenv/issues/3310
          # can be removed once a version newer than 2.6.7 is released
          brew update && brew install pyenv --head
          pyenv install 2.7.18 && pyenv global 2.7.18
          # Downgrade cmake from cmake 4 to cmake 3
          brew uninstall cmake
          pip3 install cmake==3.31 --break-system-packages
