name: Generate prebuilt archives
on:
  push:
    tags:
      - '*'
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out project
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up rust toolchain and caching
      uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
      with:
        cache: true
        key: linux-tools
        cache-workspaces: nx-decomp-tools/viking
        cache-directories: |
          download/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-16.04
          download/clang+llvm-4.0.1-x86_64-linux-gnu-Fedora-25
    - name: Generate prebuilt archives
      run: ./generate.sh
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          build/OdysseyDecomp-binaries_Linux.tar.xz
          build/OdysseyDecomp-libcxx-headers.tar.xz
        preserve_order: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        make_latest: true
